FROM python:3.13-rc-slim-bookworm

LABEL org.opencontainers.image.source=https://github.com/snicker/juicepassproxy

ENV DEBUG=false
ENV UPDATE_UDPC=false

RUN pip install --root-user-action=ignore --no-cache-dir --upgrade pip
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y tini git curl
RUN mkdir -p /juicepassproxy
RUN mkdir -p /log
RUN mkdir -p /config
COPY requirements.txt /juicepassproxy
RUN pip install --root-user-action=ignore --no-cache-dir -r /juicepassproxy/requirements.txt
COPY * /juicepassproxy
RUN chmod -f +x /juicepassproxy/*.sh

#ENTRYPOINT ["/usr/bin/tini", "--", "/juicepassproxy/docker_entrypoint.sh"]
ENTRYPOINT ["/juicepassproxy/docker_entrypoint.sh"]
